import 'package:flutter/material.dart';

import '../core/navigation/navigation.dart';

class ApiConstants {
  ApiConstants._();
  static const String apikey = "4545de32-8088-480c-adb2-6c3f6dbc978c";
  static const String baseUrl = "https://api.deepai.org/api/";
  static const String removeBackground = "https://sdk.photoroom.com/v1/segment";
  static const String backgroundApikey =
      "7c14d0b274e50c3d7ed90d0e439765f16ff2cd17";
  static const String threeDCharacter = "3d-character-generator";
  static const String surreal = "surreal-portrait-generator";
  static const String anime = "anime-portrait-generator";
  static const String apiheader = "api-key";
  static const String backgroundapiheader = "X-Api-Key";
  static const String imagefile = "image_file";
}

void onLoading() {
  showDialog(
      context: NavigationService.navigationKey.currentContext!,
      barrierDismissible: false,
      builder: (ctx) {
        return const Material(
          color: Colors.transparent,
          child: Center(
            child: CircularProgressIndicator.adaptive(),
          ),
        );
      });
}

enum Generator {
  // text2img,
  // cuteCreature,
  fantasyWorld,
  cyberpunk,
  // animePortrait,
  // oldStyle,
  renaissancePainting,
  abstractPainting,
  impressionismPainting,
  surrealGraphics,
  _3dObjects,
  origami3D,
  hologram3D,
  _3dCharacter,
  watercolorPainting,
  popArt,
  contemporaryArchitecture,
  futureArchitecture,
  watercolorArchitecture,
  fantasyCharacter,
  steampunk,
  logo,
  pixelArt,
  streetArt,
  surrealPortrait,
  animeWorld,
  fantasyPortrait,
  comicsPortrait,
  cyberpunkPortrait,
  neoNoir,
  pixelWorld,
  mangaPanel,
  _3dCartoon,
  fantasyMap,
  cyberBeast,
  dystopianLandscape,
  oceanLife,
  spaceWorld,
  comicsSuperhero,
  animeSuperhero,
  propheticVision,
  grotesqueArt,
  tribalArt,
  mysticismArt,
  urbanFashion,
  childrenBook,
  minimalisticArt,
  artDeco,
  hauntedPortrait,
  steampunkLandscape,
  artNouveau,
  baroqueArt,
  gothicArt,
  cubistArt,
  romanticArt,
  photorealisticPortrait,
  chibiCharacter,
  dreamscape,
  mechaSuit,
  abstractExpressionism,
  supernaturalCharacter,
  gladiatorArena,
  solarSystem,
  alienFlora,
  renaissanceFresco,
  depthsSea,
  fairyTaleArt,
  mythicCreature,
  postApocalyptic,
  ancientEgyptian,
  urbanGraffiti,
  wildWest,
  oldMasters,
  origamiPaper,
  carnivalScene,
  retroGame,
  actionFigure,
  greekMythology,
  undergroundCity,
  filmPoster,
  spaceshipBlueprint,
  zombieApocalypse,
  concreteJungle,
  bioluminescentLife,
  iceWorld,
  bauhausDesign,
  intergalacticBattle,
  atlantisWorld,
  samuraiArt,
  iceSculpture,
  operaCostume,
  ancientHieroglyph,
  solarFlare,
  kawaiiEmoji,
  psychedelicPoster,
  witchcraftSymbol,
  alienCivilization,
  cavePainting,
  mechanicalAnatomy,
  surrealistSculpture,
  stainedGlass,
  gothicLiterature,
  colonialPortrait,
  unrealCityscape,
  clockworkToy,
  marionetteDesign,
  postImpressionistPainting,
  tropicalParadise,
  elvenWorld,
  zentangleDesign,
  marsLife,
  brutalistArchitecture,
  politicalSatire,
  treehouseDesign,
  ancientMayanArt,
  decoupageArt,
  terrariumWorld,
  dystopianCyberpunk,
  filmCollage,
  zodiacDesign,
  robotBattle,
  playingCard,
  gothicArchitecture,
}

final Map<Generator, String> generatorMap = {
  // Generator.text2img: 'Text to Image',
  // Generator.cuteCreature: 'Cute Creature',
  Generator.fantasyWorld: 'Fantasy World',
  Generator.cyberpunk: 'Cyberpunk',
  // Generator.animePortrait: 'Anime Portrait',
  // Generator.oldStyle: 'Old Style',
  Generator.renaissancePainting: 'Renaissance Painting',
  Generator.abstractPainting: 'Abstract Painting',
  Generator.impressionismPainting: 'Impressionism Painting',
  Generator.surrealGraphics: 'Surreal Graphics',
  Generator._3dObjects: '3D Objects',
  Generator.origami3D: 'Origami 3D',
  Generator.hologram3D: 'Hologram 3D',
  Generator._3dCharacter: '3D Character',
  Generator.watercolorPainting: 'Watercolor Painting',
  Generator.popArt: 'Pop Art',
  Generator.contemporaryArchitecture: 'Contemporary Architecture',
  Generator.futureArchitecture: 'Future Architecture',
  Generator.watercolorArchitecture: 'Watercolor Architecture',
  Generator.fantasyCharacter: 'Fantasy Character',
  Generator.steampunk: 'Steampunk',
  Generator.logo: 'Logo',
  Generator.pixelArt: 'Pixel Art',
  Generator.streetArt: 'Street Art',
  Generator.surrealPortrait: 'Surreal Portrait',
  Generator.animeWorld: 'Anime World',
  Generator.fantasyPortrait: 'Fantasy Portrait',
  Generator.comicsPortrait: 'Comics Portrait',
  Generator.cyberpunkPortrait: 'Cyberpunk Portrait',
  Generator.neoNoir: 'Neo Noir',
  Generator.pixelWorld: 'Pixel World',
  Generator.mangaPanel: 'Manga Panel',
  Generator._3dCartoon: '3D Cartoon',
  Generator.fantasyMap: 'Fantasy Map',
  Generator.cyberBeast: 'Cyber Beast',
  Generator.dystopianLandscape: 'Dystopian Landscape',
  Generator.oceanLife: 'Ocean Life',
  Generator.spaceWorld: 'Space World',
  Generator.comicsSuperhero: 'Comics Superhero',
  Generator.animeSuperhero: 'Anime Superhero',
  Generator.propheticVision: 'Prophetic Vision',
  Generator.grotesqueArt: 'Grotesque Art',
  Generator.tribalArt: 'Tribal Art',
  Generator.mysticismArt: 'Mysticism Art',
  Generator.urbanFashion: 'Urban Fashion',
  Generator.childrenBook: 'Children Book',
  Generator.minimalisticArt: 'Minimalistic Art',
  Generator.artDeco: 'Art Deco',
  Generator.hauntedPortrait: 'Haunted Portrait',
  Generator.steampunkLandscape: 'Steampunk Landscape',
  Generator.artNouveau: 'Art Nouveau',
  Generator.baroqueArt: 'Baroque Art',
  Generator.gothicArt: 'Gothic Art',
  Generator.cubistArt: 'Cubist Art',
  Generator.romanticArt: 'Romantic Art',
  Generator.photorealisticPortrait: 'Photorealistic Portrait',
  Generator.chibiCharacter: 'Chibi Character',
  Generator.dreamscape: 'Dreamscape',
  Generator.mechaSuit: 'Mecha Suit',
  Generator.abstractExpressionism: 'Abstract Expressionism',
  Generator.supernaturalCharacter: 'Supernatural Character',
  Generator.gladiatorArena: 'Gladiator Arena',
  Generator.solarSystem: 'Solar System',
  Generator.alienFlora: 'Alien Flora',
  Generator.renaissanceFresco: 'Renaissance Fresco',
  Generator.depthsSea: 'Depths of the Sea',
  Generator.fairyTaleArt: 'Fairy Tale Art',
  Generator.mythicCreature: 'Mythic Creature',
  Generator.postApocalyptic: 'Post-Apocalyptic',
  Generator.ancientEgyptian: 'Ancient Egyptian',
  Generator.urbanGraffiti: 'Urban Graffiti',
  Generator.wildWest: 'Wild West',
  Generator.oldMasters: 'Old Masters',
  Generator.origamiPaper: 'Origami Paper',
  Generator.carnivalScene: 'Carnival Scene',
  Generator.retroGame: 'Retro Game',
  Generator.actionFigure: 'Action Figure',
  Generator.greekMythology: 'Greek Mythology',
  Generator.undergroundCity: 'Underground City',
  Generator.filmPoster: 'Film Poster',
  Generator.spaceshipBlueprint: 'Spaceship Blueprint',
  Generator.zombieApocalypse: 'Zombie Apocalypse',
  Generator.concreteJungle: 'Concrete Jungle',
  Generator.bioluminescentLife: 'Bioluminescent Life',
  Generator.iceWorld: 'Ice World',
  Generator.bauhausDesign: 'Bauhaus Design',
  Generator.intergalacticBattle: 'Intergalactic Battle',
  Generator.atlantisWorld: 'Atlantis World',
  Generator.samuraiArt: 'Samurai Art',
  Generator.iceSculpture: 'Ice Sculpture',
  Generator.operaCostume: 'Opera Costume',
  Generator.ancientHieroglyph: 'Ancient Hieroglyph',
  Generator.solarFlare: 'Solar Flare',
  Generator.kawaiiEmoji: 'Kawaii Emoji',
  Generator.psychedelicPoster: 'Psychedelic Poster',
  Generator.witchcraftSymbol: 'Witchcraft Symbol',
  Generator.alienCivilization: 'Alien Civilization',
  Generator.cavePainting: 'Cave Painting',
  Generator.mechanicalAnatomy: 'Mechanical Anatomy',
  Generator.surrealistSculpture: 'Surrealist Sculpture',
  Generator.stainedGlass: 'Stained Glass',
  Generator.gothicLiterature: 'Gothic Literature',
  Generator.colonialPortrait: 'Colonial Portrait',
  Generator.unrealCityscape: 'Unreal Cityscape',
  Generator.clockworkToy: 'Clockwork Toy',
  Generator.marionetteDesign: 'Marionette Design',
  Generator.postImpressionistPainting: 'Post-Impressionist Painting',
  Generator.tropicalParadise: 'Tropical Paradise',
  Generator.elvenWorld: 'Elven World',
  Generator.zentangleDesign: 'Zentangle Design',
  Generator.marsLife: 'Life on Mars',
  Generator.brutalistArchitecture: 'Brutalist Architecture',
  Generator.politicalSatire: 'Political Satire',
  Generator.treehouseDesign: 'Treehouse Design',
  Generator.ancientMayanArt: 'Ancient Mayan Art',
  Generator.decoupageArt: 'Decoupage Art',
  Generator.terrariumWorld: 'Terrarium World',
  Generator.dystopianCyberpunk: 'Dystopian Cyberpunk',
  Generator.filmCollage: 'Film Collage',
  Generator.zodiacDesign: 'Zodiac Design',
  Generator.robotBattle: 'Robot Battle',
  Generator.playingCard: 'Playing Card',
  Generator.gothicArchitecture: 'Gothic Architecture',
};


final Map<Generator, String> linksMap = {
  // Generator.text2img: "https://api.deepai.org/api/text2img",
  // Generator.cuteCreature: "https://api.deepai.org/api/cute-creature-generator",
  Generator.fantasyWorld: "https://api.deepai.org/api/fantasy-world-generator",
  Generator.cyberpunk: "https://api.deepai.org/api/cyberpunk-generator",
  // Generator.animePortrait:
  //     "https://api.deepai.org/api/anime-portrait-generator",
  // Generator.oldStyle: "https://api.deepai.org/api/old-style-generator",
  Generator.renaissancePainting:
      "https://api.deepai.org/api/renaissance-painting-generator",
  Generator.abstractPainting:
      "https://api.deepai.org/api/abstract-painting-generator",
  Generator.impressionismPainting:
      "https://api.deepai.org/api/impressionism-painting-generator",
  Generator.surrealGraphics:
      "https://api.deepai.org/api/surreal-graphics-generator",
  Generator._3dObjects: "https://api.deepai.org/api/3d-objects-generator",
  Generator.origami3D: "https://api.deepai.org/api/origami-3d-generator",
  Generator.hologram3D: "https://api.deepai.org/api/hologram-3d-generator",
  Generator._3dCharacter: "https://api.deepai.org/api/3d-character-generator",
  Generator.watercolorPainting:
      "https://api.deepai.org/api/watercolor-painting-generator",
  Generator.popArt: "https://api.deepai.org/api/pop-art-generator",
  Generator.contemporaryArchitecture:
      "https://api.deepai.org/api/contemporary-architecture-generator",
  Generator.futureArchitecture:
      "https://api.deepai.org/api/future-architecture-generator",
  Generator.watercolorArchitecture:
      "https://api.deepai.org/api/watercolor-architecture-generator",
  Generator.fantasyCharacter:
      "https://api.deepai.org/api/fantasy-character-generator",
  Generator.steampunk: "https://api.deepai.org/api/steampunk-generator",
  Generator.logo: "https://api.deepai.org/api/logo-generator",
  Generator.pixelArt: "https://api.deepai.org/api/pixel-art-generator",
  Generator.streetArt: "https://api.deepai.org/api/street-art-generator",
  Generator.surrealPortrait:
      "https://api.deepai.org/api/surreal-portrait-generator",
  Generator.animeWorld: "https://api.deepai.org/api/anime-world-generator",
  Generator.fantasyPortrait:
      "https://api.deepai.org/api/fantasy-portrait-generator",
  Generator.comicsPortrait:
      "https://api.deepai.org/api/comics-portrait-generator",
  Generator.cyberpunkPortrait:
      "https://api.deepai.org/api/cyberpunk-portrait-generator",
  Generator.neoNoir: "https://api.deepai.org/api/neo-noir-generator",
  Generator.pixelWorld: "https://api.deepai.org/api/pixel-world-generator",
  Generator.mangaPanel: "https://api.deepai.org/api/manga-panel-genarator",
  Generator._3dCartoon: "https://api.deepai.org/api/3d-cartoon-generator",
  Generator.fantasyMap: "https://api.deepai.org/api/fantasy-map-generator",
  Generator.cyberBeast: "https://api.deepai.org/api/cyber-beast-generator",
  Generator.dystopianLandscape:
      "https://api.deepai.org/api/dystopian-landscape-generator",
  Generator.oceanLife: "https://api.deepai.org/api/ocean-life-generator",
  Generator.spaceWorld: "https://api.deepai.org/api/space-world-generator",
  Generator.comicsSuperhero:
      "https://api.deepai.org/api/comics-superhero-generator",
  Generator.animeSuperhero:
      "https://api.deepai.org/api/anime-superhero-generator",
  Generator.propheticVision:
      "https://api.deepai.org/api/prophetic-vision-generator",
  Generator.grotesqueArt: "https://api.deepai.org/api/grotesque-art-generator",
  Generator.tribalArt: "https://api.deepai.org/api/tribal-art-generator",
  Generator.mysticismArt: "https://api.deepai.org/api/mysticism-art-generator",
  Generator.urbanFashion: "https://api.deepai.org/api/urban-fashion-generator",
  Generator.childrenBook: "https://api.deepai.org/api/children-book-generator",
  Generator.minimalisticArt:
      "https://api.deepai.org/api/minimalistic-art-generator",
  Generator.artDeco: "https://api.deepai.org/api/art-deco-generator",
  Generator.hauntedPortrait:
      "https://api.deepai.org/api/haunted-portrait-generator",
  Generator.steampunkLandscape:
      "https://api.deepai.org/api/steampunk-landscape-generator",
  Generator.artNouveau: "https://api.deepai.org/api/art-nouveau-generator",
  Generator.baroqueArt: "https://api.deepai.org/api/baroque-art-generator",
  Generator.gothicArt: "https://api.deepai.org/api/gothic-art-generator",
  Generator.cubistArt: "https://api.deepai.org/api/cubist-art-generator",
  Generator.romanticArt: "https://api.deepai.org/api/romantic-art-generator",
  Generator.photorealisticPortrait:
      "https://api.deepai.org/api/photorealistic-portrait-generator",
  Generator.chibiCharacter:
      "https://api.deepai.org/api/chibi-character-generator",
  Generator.dreamscape: "https://api.deepai.org/api/dreamscape-generator",
  Generator.mechaSuit: "https://api.deepai.org/api/mecha-suit-generator",
  Generator.abstractExpressionism:
      "https://api.deepai.org/api/abstract-expressionism-generator",
  Generator.supernaturalCharacter:
      "https://api.deepai.org/api/supernatural-character-generator",
  Generator.gladiatorArena:
      "https://api.deepai.org/api/gladiator-arena-generator",
  Generator.solarSystem: "https://api.deepai.org/api/solar-system-generator",
  Generator.alienFlora: "https://api.deepai.org/api/alien-flora-generator",
  Generator.renaissanceFresco:
      "https://api.deepai.org/api/renaissance-fresco-generator",
  Generator.depthsSea: "https://api.deepai.org/api/depths-sea-generator",
  Generator.fairyTaleArt: "https://api.deepai.org/api/fairy-tale-art-generator",
  Generator.mythicCreature:
      "https://api.deepai.org/api/mythic-creature-generator",
  Generator.postApocalyptic:
      "https://api.deepai.org/api/post-apocalyptic-generator",
  Generator.ancientEgyptian:
      "https://api.deepai.org/api/ancient-egyptian-generator",
  Generator.urbanGraffiti:
      "https://api.deepai.org/api/urban-graffiti-generator",
  Generator.wildWest: "https://api.deepai.org/api/wild-west-generator",
  Generator.oldMasters: "https://api.deepai.org/api/old-masters-generator",
  Generator.origamiPaper: "https://api.deepai.org/api/origami-paper-generator",
  Generator.carnivalScene:
      "https://api.deepai.org/api/carnival-scene-generator",
  Generator.retroGame: "https://api.deepai.org/api/retro-game-generator",
  Generator.actionFigure: "https://api.deepai.org/api/action-figure-generator",
  Generator.greekMythology:
      "https://api.deepai.org/api/greek-mythology-generator",
  Generator.undergroundCity:
      "https://api.deepai.org/api/underground-city-generator",
  Generator.filmPoster: "https://api.deepai.org/api/film-poster-generator",
  Generator.spaceshipBlueprint:
      "https://api.deepai.org/api/spaceship-blueprint-generator",
  Generator.zombieApocalypse:
      "https://api.deepai.org/api/zombie-apocalypse-generator",
  Generator.concreteJungle:
      "https://api.deepai.org/api/concrete-jungle-generator",
  Generator.bioluminescentLife:
      "https://api.deepai.org/api/bioluminescent-life-generator",
  Generator.iceWorld: "https://api.deepai.org/api/ice-world-generator",
  Generator.bauhausDesign:
      "https://api.deepai.org/api/bauhaus-design-generator",
  Generator.intergalacticBattle:
      "https://api.deepai.org/api/intergalactic-battle-generator",
  Generator.atlantisWorld:
      "https://api.deepai.org/api/atlantis-world-generator",
  Generator.samuraiArt: "https://api.deepai.org/api/samurai-art-generator",
  Generator.iceSculpture: "https://api.deepai.org/api/ice-sculpture-generator",
  Generator.operaCostume: "https://api.deepai.org/api/opera-costume-generator",
  Generator.ancientHieroglyph:
      "https://api.deepai.org/api/ancient-hieroglyph-generator",
  Generator.solarFlare: "https://api.deepai.org/api/solar-flare-generator",
  Generator.kawaiiEmoji: "https://api.deepai.org/api/kawaii-emoji-generator",
  Generator.psychedelicPoster:
      "https://api.deepai.org/api/psychedelic-poster-generator",
  Generator.witchcraftSymbol:
      "https://api.deepai.org/api/witchcraft-symbol-generator",
  Generator.alienCivilization:
      "https://api.deepai.org/api/alien-civilization-generator",
  Generator.cavePainting: "https://api.deepai.org/api/cave-painting-generator",
  Generator.mechanicalAnatomy:
      "https://api.deepai.org/api/mechanical-anatomy-generator",
  Generator.surrealistSculpture:
      "https://api.deepai.org/api/surrealist-sculpture-generator",
  Generator.stainedGlass: "https://api.deepai.org/api/stained-glass-generator",
  Generator.gothicLiterature:
      "https://api.deepai.org/api/gothic-literature-generator",
  Generator.colonialPortrait:
      "https://api.deepai.org/api/colonial-portrait-generator",
  Generator.unrealCityscape:
      "https://api.deepai.org/api/unreal-cityscape-generator",
  Generator.clockworkToy: "https://api.deepai.org/api/clockwork-toy-generator",
  Generator.marionetteDesign:
      "https://api.deepai.org/api/marionette-design-generator",
  Generator.postImpressionistPainting:
      "https://api.deepai.org/api/post-impressionist-painting-generator",
  Generator.tropicalParadise:
      "https://api.deepai.org/api/tropical-paradise-generator",
  Generator.elvenWorld: "https://api.deepai.org/api/elven-world-generator",
  Generator.zentangleDesign:
      "https://api.deepai.org/api/zentangle-design-generator",
  Generator.marsLife: "https://api.deepai.org/api/mars-life-generator",
  Generator.brutalistArchitecture:
      "https://api.deepai.org/api/brutalist-architecture-generator",
  Generator.politicalSatire:
      "https://api.deepai.org/api/political-satire-generator",
  Generator.treehouseDesign:
      "https://api.deepai.org/api/treehouse-design-generator",
  Generator.ancientMayanArt:
      "https://api.deepai.org/api/ancient-mayan-art-generator",
  Generator.decoupageArt: "https://api.deepai.org/api/decoupage-art-generator",
  Generator.terrariumWorld:
      "https://api.deepai.org/api/terrarium-world-generator",
  Generator.dystopianCyberpunk:
      "https://api.deepai.org/api/dystopian-cyberpunk-generator",
  Generator.filmCollage: "https://api.deepai.org/api/film-collage-generator",
  Generator.zodiacDesign: "https://api.deepai.org/api/zodiac-design-generator",
  Generator.robotBattle: "https://api.deepai.org/api/robot-battle-generator",
  Generator.playingCard: "https://api.deepai.org/api/playing-card-generator",
  Generator.gothicArchitecture:
      "https://api.deepai.org/api/gothic-architecture-generator",
};
List<String> links = [
  "https://api.deepai.org/api/text2img",
  "https://api.deepai.org/api/cute-creature-generator",
  "https://api.deepai.org/api/fantasy-world-generator",
  "https://api.deepai.org/api/cyberpunk-generator",
  "https://api.deepai.org/api/anime-portrait-generator",
  "https://api.deepai.org/api/old-style-generator",
  "https://api.deepai.org/api/renaissance-painting-generator",
  "https://api.deepai.org/api/abstract-painting-generator",
  "https://api.deepai.org/api/impressionism-painting-generator",
  "https://api.deepai.org/api/surreal-graphics-generator",
  "https://api.deepai.org/api/3d-objects-generator",
  "https://api.deepai.org/api/origami-3d-generator",
  "https://api.deepai.org/api/hologram-3d-generator",
  "https://api.deepai.org/api/3d-character-generator",
  "https://api.deepai.org/api/watercolor-painting-generator",
  "https://api.deepai.org/api/pop-art-generator",
  "https://api.deepai.org/api/contemporary-architecture-generator",
  "https://api.deepai.org/api/future-architecture-generator",
  "https://api.deepai.org/api/watercolor-architecture-generator",
  "https://api.deepai.org/api/fantasy-character-generator",
  "https://api.deepai.org/api/steampunk-generator",
  "https://api.deepai.org/api/logo-generator",
  "https://api.deepai.org/api/pixel-art-generator",
  "https://api.deepai.org/api/street-art-generator",
  "https://api.deepai.org/api/surreal-portrait-generator",
  "https://api.deepai.org/api/anime-world-generator",
  "https://api.deepai.org/api/fantasy-portrait-generator",
  "https://api.deepai.org/api/comics-portrait-generator",
  "https://api.deepai.org/api/cyberpunk-portrait-generator",
  "https://api.deepai.org/api/neo-noir-generator",
  "https://api.deepai.org/api/pixel-world-generator",
  "https://api.deepai.org/api/manga-panel-genarator",
  "https://api.deepai.org/api/3d-cartoon-generator",
  "https://api.deepai.org/api/fantasy-map-generator",
  "https://api.deepai.org/api/cyber-beast-generator",
  "https://api.deepai.org/api/dystopian-landscape-generator",
  "https://api.deepai.org/api/ocean-life-generator",
  "https://api.deepai.org/api/space-world-generator",
  "https://api.deepai.org/api/comics-superhero-generator",
  "https://api.deepai.org/api/anime-superhero-generator",
  "https://api.deepai.org/api/prophetic-vision-generator",
  "https://api.deepai.org/api/grotesque-art-generator",
  "https://api.deepai.org/api/tribal-art-generator",
  "https://api.deepai.org/api/mysticism-art-generator",
  "https://api.deepai.org/api/urban-fashion-generator",
  "https://api.deepai.org/api/children-book-generator",
  "https://api.deepai.org/api/minimalistic-art-generator",
  "https://api.deepai.org/api/art-deco-generator",
  "https://api.deepai.org/api/haunted-portrait-generator",
  "https://api.deepai.org/api/steampunk-landscape-generator",
  "https://api.deepai.org/api/art-nouveau-generator",
  "https://api.deepai.org/api/baroque-art-generator",
  "https://api.deepai.org/api/gothic-art-generator",
  "https://api.deepai.org/api/cubist-art-generator",
  "https://api.deepai.org/api/romantic-art-generator",
  "https://api.deepai.org/api/photorealistic-portrait-generator",
  "https://api.deepai.org/api/chibi-character-generator",
  "https://api.deepai.org/api/dreamscape-generator",
  "https://api.deepai.org/api/mecha-suit-generator",
  "https://api.deepai.org/api/abstract-expressionism-generator",
  "https://api.deepai.org/api/supernatural-character-generator",
  "https://api.deepai.org/api/gladiator-arena-generator",
  "https://api.deepai.org/api/solar-system-generator",
  "https://api.deepai.org/api/alien-flora-generator",
  "https://api.deepai.org/api/renaissance-fresco-generator",
  "https://api.deepai.org/api/depths-sea-generator",
  "https://api.deepai.org/api/fairy-tale-art-generator",
  "https://api.deepai.org/api/mythic-creature-generator",
  "https://api.deepai.org/api/post-apocalyptic-generator",
  "https://api.deepai.org/api/ancient-egyptian-generator",
  "https://api.deepai.org/api/urban-graffiti-generator",
  "https://api.deepai.org/api/wild-west-generator",
  "https://api.deepai.org/api/old-masters-generator",
  "https://api.deepai.org/api/origami-paper-generator",
  "https://api.deepai.org/api/carnival-scene-generator",
  "https://api.deepai.org/api/retro-game-generator",
  "https://api.deepai.org/api/action-figure-generator",
  "https://api.deepai.org/api/greek-mythology-generator",
  "https://api.deepai.org/api/underground-city-generator",
  "https://api.deepai.org/api/film-poster-generator",
  "https://api.deepai.org/api/spaceship-blueprint-generator",
  "https://api.deepai.org/api/zombie-apocalypse-generator",
  "https://api.deepai.org/api/concrete-jungle-generator",
  "https://api.deepai.org/api/bioluminescent-life-generator",
  "https://api.deepai.org/api/ice-world-generator",
  "https://api.deepai.org/api/bauhaus-design-generator",
  "https://api.deepai.org/api/intergalactic-battle-generator",
  "https://api.deepai.org/api/atlantis-world-generator",
  "https://api.deepai.org/api/samurai-art-generator",
  "https://api.deepai.org/api/ice-sculpture-generator",
  "https://api.deepai.org/api/opera-costume-generator",
  "https://api.deepai.org/api/ancient-hieroglyph-generator",
  "https://api.deepai.org/api/solar-flare-generator",
  "https://api.deepai.org/api/kawaii-emoji-generator",
  "https://api.deepai.org/api/psychedelic-poster-generator",
  "https://api.deepai.org/api/witchcraft-symbol-generator",
  "https://api.deepai.org/api/alien-civilization-generator",
  "https://api.deepai.org/api/cave-painting-generator",
  "https://api.deepai.org/api/mechanical-anatomy-generator",
  "https://api.deepai.org/api/surrealist-sculpture-generator",
  "https://api.deepai.org/api/stained-glass-generator",
  "https://api.deepai.org/api/gothic-literature-generator",
  "https://api.deepai.org/api/colonial-portrait-generator",
  "https://api.deepai.org/api/unreal-cityscape-generator",
  "https://api.deepai.org/api/clockwork-toy-generator",
  "https://api.deepai.org/api/marionette-design-generator",
  "https://api.deepai.org/api/post-impressionist-painting-generator",
  "https://api.deepai.org/api/tropical-paradise-generator",
  "https://api.deepai.org/api/elven-world-generator",
  "https://api.deepai.org/api/zentangle-design-generator",
  "https://api.deepai.org/api/mars-life-generator",
  "https://api.deepai.org/api/brutalist-architecture-generator",
  "https://api.deepai.org/api/political-satire-generator",
  "https://api.deepai.org/api/treehouse-design-generator",
  "https://api.deepai.org/api/ancient-mayan-art-generator",
  "https://api.deepai.org/api/decoupage-art-generator",
  "https://api.deepai.org/api/terrarium-world-generator",
  "https://api.deepai.org/api/dystopian-cyberpunk-generator",
  "https://api.deepai.org/api/film-collage-generator",
  "https://api.deepai.org/api/zodiac-design-generator",
  "https://api.deepai.org/api/robot-battle-generator",
  "https://api.deepai.org/api/playing-card-generator",
  "https://api.deepai.org/api/gothic-architecture-generator"
];
